on: [push]

jobs:
  build_deploy:
    name: Build with Hugo and deploy to gh page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true 
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Merge theme submodule
        run: git submodule update --remote --merge

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -t cleanwhite --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true